name: Build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      os:
        required: true
        type: string
      buildArgs:
        required: true
        type: string
      exportPath:
        required: true
        type: string
      artifactName:
        required: true
        type: string
      cacheLibrariesPath:
        required: true
        type: string
      cachePath:
        required: true
        type: string
      artifactPath:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore Libraries Cache
        id: cache-libraries
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.haxelib
            ~/.hxcpp
          key: ${{ inputs.cacheLibrariesPath }}

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Restore Build Cache
        id: cache-build
        uses: actions/cache/restore@v4
        with:
          path: |
            export/release/${{ inputs.exportPath }}
          key: ${{ inputs.cachePath }}

      - name: Build ${{ inputs.name }}
        run: |
          haxelib run lime build ${{ inputs.buildArgs }}

      - name: Remove Firebase from build.gradle
        if: ${{ inputs.exportPath == 'android' }}
        run: |
          find . -name "build.gradle" -exec sed -i '/firebaseCrashlytics()/d' {} \;
          find . -name "build.gradle" -exec sed -i '/google-services/d' {} \;
          find . -name "build.gradle" -exec sed -i '/com.google.firebase/d' {} \;

      - name: Upload ${{ inputs.name }} Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifactName }}
          path: ${{ inputs.artifactPath }}
          retention-days: 7