name: Build Windows and Linux

on:
  workflow_dispatch:

jobs:
  BuildDesktopCache:
    name: Build Desktop Cache
    permissions: write-all
    uses: ./.github/workflows/dependencies.yml
    with:
      os: ubuntu-24.04
      setupScript: sh ./setup/unix.sh
      CACHE_NAME: P-Slice.1.0.desktop-cache

  BuildDesktop:
    name: Build Desktop
    needs: BuildDesktopCache
    permissions: write-all
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-2022
            buildArgs: "windows -final"
            exportPath: windows
            artifactName: PSlice-Windows
            cacheLibrariesPath: P-Slice.1.0.desktop-cache
            cachePath: P-Slice.1.0.build-windows
            artifactPath: export\release\windows\bin\*
          - name: Linux
            os: ubuntu-22.04
            buildArgs: "linux -final"
            exportPath: linux
            artifactName: PSlice-Linux
            cachePath: P-Slice.1.0.build-linux
            cacheLibrariesPath: P-Slice.1.0.desktop-cache
            artifactPath: export/release/linux/bin/*
    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      cacheLibrariesPath: ${{ matrix.cacheLibrariesPath }}
      exportPath: ${{ matrix.exportPath }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}
      cachePath: ${{ matrix.cachePath }}
